name: "Terraform action"
on:
  push:
    branches:
      - main
  pull_request:

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for the github bot to comment on our pull requests

env:
  AWS_REGION: eu-west-1 # Seans region
  IAM_ROLE_ARN: arn:aws:iam::924511948270:role/Rent-A-CrowdDatabaseLevelupGithubActions

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: .
    
    steps:
      - name: Git checkout 
        uses: actions/checkout

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{ enc.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init 
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -no-color

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply # get's triggered only when there's a push (or merge) request to the main branch
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' 
        run: terraform apply -auto-approve -input=false 

      